/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticoliRouteImport } from './routes/articoli'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as ComunicatiRouteImport } from './routes/comunicati'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as LibroRouteImport } from './routes/libro'
import { Route as PrivacyRouteImport } from './routes/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticoliRoute = ArticoliRouteImport.update({
  id: '/articoli',
  path: '/articoli',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicatiRoute = ComunicatiRouteImport.update({
  id: '/comunicati',
  path: '/comunicati',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroRoute = LibroRouteImport.update({
  id: '/libro',
  path: '/libro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articoli': typeof ArticoliRoute
  '/biografia': typeof BiografiaRoute
  '/comunicati': typeof ComunicatiRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/libro': typeof LibroRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articoli': typeof ArticoliRoute
  '/biografia': typeof BiografiaRoute
  '/comunicati': typeof ComunicatiRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/libro': typeof LibroRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articoli': typeof ArticoliRoute
  '/biografia': typeof BiografiaRoute
  '/comunicati': typeof ComunicatiRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/libro': typeof LibroRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articoli'
    | '/biografia'
    | '/comunicati'
    | '/contatti'
    | '/cookie'
    | '/libro'
    | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articoli'
    | '/biografia'
    | '/comunicati'
    | '/contatti'
    | '/cookie'
    | '/libro'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/articoli'
    | '/biografia'
    | '/comunicati'
    | '/contatti'
    | '/cookie'
    | '/libro'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticoliRoute: typeof ArticoliRoute
  BiografiaRoute: typeof BiografiaRoute
  ComunicatiRoute: typeof ComunicatiRoute
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  LibroRoute: typeof LibroRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articoli': {
      id: '/articoli'
      path: '/articoli'
      fullPath: '/articoli'
      preLoaderRoute: typeof ArticoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicati': {
      id: '/comunicati'
      path: '/comunicati'
      fullPath: '/comunicati'
      preLoaderRoute: typeof ComunicatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro': {
      id: '/libro'
      path: '/libro'
      fullPath: '/libro'
      preLoaderRoute: typeof LibroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticoliRoute: ArticoliRoute,
  BiografiaRoute: BiografiaRoute,
  ComunicatiRoute: ComunicatiRoute,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  LibroRoute: LibroRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
